### ISSUE TITLE
signing when using STS credentials

### ISSUE THREAD

**Issue by rafaurl** [iksteen/aws-request-signer#1]
I just tested for signing sp-api calls and it works like a charm, but when trying to sign requests made with temporary credentials obtained from STS it failed. In https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html says that:

`

You can use temporary security credentials provided by the AWS Security Token Service (AWS STS) to sign a request. The process is the same as using long-term credentials, but requires an additional HTTP header or query string parameter for the security token. The name of the header or query string parameter is X-Amz-Security-Token, and the value is the session token (the string you received from AWS STS when you obtained temporary security credentials).

When you add the X-Amz-Security-Token parameter to the query string, some services require that you include this parameter in the canonical (signed) request. For other services, you add this parameter at the end, after you calculate the signature. For details, see the API reference documentation for that service.
`
so I think it would be great if you could add an extra parameter "session_token" in the __init__, and if it is not None, add the header X-Amz-Security-Token with the same value received.

**Comment by iksteen** [comment]
I'll look into this when I have time! Thanks for the suggestion on how to implement it, should make it trivial to add. But I'll want to see it working myself before I commit myself to the new interface.

**Comment by iksteen** [comment]
Fixed in master. Thanks @ajpl!
