### ISSUE TITLE
Allow aws_request_signer() content_hash to be None for HEAD & DELETE methods

### ISSUE THREAD

**Issue by alvassin** [iksteen/aws-request-signer#2]
Currently it is necessary to specify `content_hash` argument to empty string sha256 hash for HEAD & DELETE requests to `aws_request_signer()` method, but this can be [omitted for GET requests](https://github.com/iksteen/aws-request-signer/blob/master/aws_request_signer/__init__.py#L182).

What do you thing about HEAD & DELETE methods? 
If you are ok about that idea, i would be glad to make PR.

**Comment by iksteen** [comment]
Absolutely agree, go for it!

**Comment by alvassin** [comment]
@iksteen, could you check the PR please?

**Comment by alvassin** [comment]
Excuse me for disturbing, could you please release new version on pypi (1.1.0, need that changes in my library)?

**Comment by iksteen** [comment]
Just released 1.1.0.
