### ISSUE TITLE
Why x-amz-date is lower case and not the X-Amz-Date in the headers ?

### ISSUE THREAD

**Issue by pghole** [iksteen/aws-request-signer#6]
I am confused on this because in some requests using boto3, I saw the header name X-Amz-Date is uppercase with every first letter.

But in our code, the header is x-amz-date .
       
[extra_headers]( https://github.com/iksteen/aws-request-signer/blob/2e498db0aa1b84bc614eca815b89c1b17c9731f6/aws_request_signer/__init__.py#L192) = {"x-amz-content-sha256": content_hash, "x-amz-date": timestamp}

Am I missing something ?

**Comment by iksteen** [comment]
HTTP headers are case insensitive. AWS' documentation itself mentions lower case headers too: https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html

**Comment by pghole** [comment]
@iksteen Thanks. Do these headers need to be ASCII ordered or they can be random . 

For eg - {"Authorisation":"xyz", "x-amz-date": timestamp} 
OR 
 { "x-amz-date": timestamp, "Authorisation":"xyz"}

 is valid. Or the order really does not matter ?

**Comment by iksteen** [comment]
Doesn't matter, it'll be sorted by aws-request-signer as per the AWS specs.

**Comment by pghole** [comment]
@iksteen In the https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html , I was looking at line "GET ?lifecycle HTTP/1.1" and in that "x-amz-date" is sent before "x-amz-content-sha256". So the order of headers at request(python requests package) level do not matter ?

**Comment by iksteen** [comment]
That is correct, the signing algorithm sorts the headers before calculating the signature at both ends (the client library and AWS). There's no guarantee the headers don't get reordered by proxies / middleware / etc anyway.
